# Generated by Django 5.0.6 on 2024-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_generalbook_image_url_technicalbook_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalbook',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technicalbook',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
