# Generated by Django 5.0.6 on 2024-06-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_login_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
